/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef __GENX320_ERC_H__
#define __GENX320_ERC_H__
#include "../api.h"

#define ERC_REF_PERIOD_DEFAULT 100
#define ERC_TD_EVENT_COUNT_MAX 20000ll
#define ERC_TD_EVENT_COUNT_DEFAULT 1000

/// @brief Initialize ERC Configuration for GenX320
/// @param config ERC configuration structure
/// @return 0
int genx320_erc_init(struct psee_controls *controls);

/// @brief Toggles ERC activation
/// @param en Desired state. en = true means ERC active, and en = false means ERC inactive.
/// @note When ERC is inactive, all the events generated by the sensor are transmitted. Potential
/// bandwidth limitation might occur.
/// @return 0 on success
int genx320_erc_enable(struct psee_controls *controls, u32 en);

/// @brief Sets the target CD event rate of the ERC
/// @param config ERC configuration structure
/// @param rate Event rate expressed in events per second
/// @note This method and @ref genx320_erc_set_event_rate operate over the same registers. It is
/// @return true on success
int genx320_erc_set_event_rate(struct psee_controls *controls, s64 rate);
#endif // __GENX320_ERC_H__
